# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantile_type7 <- function(x, p) {
    .Call(`_BFRdist_quantile_type7`, x, p)
}

estimateBFR_cpp <- function(x) {
    .Call(`_BFRdist_estimateBFR_cpp`, x)
}

